package org.satou.gtecore.datagen;

public class Lang {

    public static void init(CommonLanguageProvider provider) {
        provider.add("config.gtecore.option.superPeace","Super Peace Mode","超级和平模式");
        provider.add("config.gtecore.option.durationMultiplier", "recipe time multiplier", "配方时间倍率");
        provider.add("block.gtecore.steam_op", "Steam Ore Processing Factory", "蒸汽矿物处理厂");
        provider.add("config.screen.gtecore", "gtecore configure menu", "gtecore配置菜单");
        provider.add("gtecore.steam_op_recipe", "Steam Ore Processing Factory", "蒸汽矿物处理厂");
        provider.add("itemGroup.gtecore.gtecore_machines", "GregTech Easy Machines", "格雷科技Easy机器");
        provider.add("itemGroup.gtecore.gtecore_items", "Gregtech Easy Items", "格雷科技Easy物品");
        provider.add("com.gtecore.tooltips.addbygtecore", "Added by GTECore ", "由GTECore添加");
        provider.add("com.gtecore.tooltips.steam_op", "1B parallels and all recipe will finish in 1tick，support all input and output machine parts", "10亿并行，并且所有配方1tick执行完毕，支持所有类型的输入输出仓室");
        provider.add("com.gtecore.tooltips.chemistry_terminator", "The magical machine has overturned the existence of chemistry and physics, and its emergence undoubtedly marks the end of chemistry", "神奇的机器，颠覆了化学与物理的存在，它的出现无疑代表着化学的终结");
        provider.add("block.gtecore.chemistry_terminator", "Chemistry Terminator", "化学终结者");
        provider.add("gtecore.chemistry_terminator_recipe", "Chemistry Terminator", "化学终结者");
        provider.add("block.gtecore.ten_in_one", "Ten in One General Processing Factory", "十合一通用处理工厂");
        provider.add("item.gtecore.super_string_processor", "Super String Processor", "超弦处理器");
        provider.add("item.gtecore.super_string_processor_assembly", "Super String Processor Assembly", "超弦处理器集群");
        provider.add("item.gtecore.super_string_processor_computer", "Super String Processor Computer", "超弦处理器超级计算机");
        provider.add("item.gtecore.super_string_processor_mainframe", "Super String Processor Mainframe", "超弦处理器主机");
        provider.add("item.gtecore.super_string_processor.tooltip.0", "§7 Circuits from the Superstring Dimension", "§7来自超弦维度的电路");
        provider.add("item.gtecore.super_string_processor.tooltip.1", "§dZPM-level circuits", "§dZPM级电路");
        provider.add("item.gtecore.super_string_processor_assembly.tooltip.0", "§7 Circuits from the Superstring Dimension", "§7来自超弦维度的电路");
        provider.add("item.gtecore.super_string_processor_assembly.tooltip.1", "§dUV-level circuits", "§dUV级电路");
        provider.add("item.gtecore.super_string_processor_computer.tooltip.0", "§7 Circuits from the Superstring Dimension", "§7来自超弦维度的电路");
        provider.add("item.gtecore.super_string_processor_computer.tooltip.1", "§dUHV-level circuits", "§dUHV级电路");
        provider.add("item.gtecore.super_string_processor_mainframe.tooltip.0", "§7 Circuits from the Superstring Dimension", "§7来自超弦维度的电路");
        provider.add("item.gtecore.super_string_processor_mainframe.tooltip.1", "§dUEV-level circuits", "§dUEV级电路");
        provider.add("com.gtecore.tooltips.super_fusion_reactor", "Support 1T OC, Very Fast!", "支持1TOC,再也不用慢慢等聚变了!");
        provider.add("block.gtecore.super_fusion_reactor", "Super Fusion Reactor", "超级聚变反应堆");
        provider.add("gtecore.super_fusion_reactor_recipe", "Super Fusion Reactor", "超级聚变反应堆");
        provider.add("block.gtecore.distillation_tower_easy", "Distillation Tower Easy", "蒸馏塔简单版");
        provider.add("block.gtecore.super_string_casing", "§d Super String Casing", "§d超弦外壳");
        provider.add("block.gtecore.super_string_mixer", "§d Super String Mixer", "§d超弦搅拌机");
        provider.add("gtecore.super_string_mixing", "§d Super String Mixing", "§d超弦搅拌");
        provider.add("block.gtecore.string_of_creation", "§d String Of Creation", "§d创世之弦");
        provider.add("gtecore.string_of_creation", "§d String Of Creation", "§d创世之弦");
        provider.add("block.gtecore.super_string_oscillator_array", "§d Super String Oscillator Array", "§d超弦震荡阵列");
        provider.add("gtecore.super_string_oscillator_array", "§d Super String Oscillator Array", "§d超弦震荡阵列");
        provider.add("block.gtecore.chord_of_all_things", "§d Chord Of All Things", "§d 万物之弦");
        provider.add("gtecore.chord_of_all_things", "§d Chord Of All Things", "§d 万物之弦");
        provider.add("item.gtecore.super_string_circuit_board", "§d Super String Circuit Board", "§d 超弦电路基板");
        provider.add("item.gtecore.super_string_printed_circuit_board", "§d Super String Printed Circuit Board", "§d 超弦电路印刷基板");
        provider.add("item.gtecore.original_string", "§d Original String", "§d起源之弦");
        provider.add("item.gtecore.alpha_string", "§d α String", "§d α弦");
        provider.add("item.gtecore.beta_string", "§d β String", "§d β弦");
        provider.add("item.gtecore.gamma_string", "§d γ String", "§d γ弦");
        provider.add("block.gtecore.easy_fluid_drilling_rig", "Easy Fluid Drilling", "简单流体钻机");
        provider.add("gtecore.easy_fluid", "Easy Fluid", "简单流体");
        provider.add("block.gtecore.not_hard_fluid_drilling_rig", "Not Hard Fluid Drilling Rig", "不难流体钻机");
        provider.add("block.gtecore.molecular_separators", "§3Molecular Separators", "§3分子离析者");
        provider.add("gtecore.molecular_separators", "§3Molecular Separators", "§3分子离析者");
        provider.add("block.gtecore.easy_box", "§6Easy §3B§2o§1x ", "§6简§3单§2之§1盒");
        provider.add("gtecore.easy_box", "§6Easy §3B§2o§1x ", "§6简§3单§2之§1盒");
        provider.add("block.gtecore.integrated_petrochemical_plant", "Integrated Petrochemical Plant", "综合石化工厂");
        provider.add("gtecore.integrated_petrochemical_plant", "Integrated Petrochemical Plant", "综合石化工厂");
        provider.add("gtecore.ore_process_center", "§6Ore Processing", "§6矿石处理");
        provider.add("block.gtecore.ore_process_center", "§6Ore Processing Center", "§6矿石处理中心");
        provider.add("com.gtecore.ore_process_center.tooltips.0", "§The §6Ore Processing Center§r has seven different types of recipes", "§6矿石处理中心§r拥有七种不同类型的配方");
        provider.add("com.gtecore.ore_process_center.tooltips.1", "Circuit 1: Crushing-Crushing-Washing", "电路1: 粉碎-粉碎-洗矿");
        provider.add("com.gtecore.ore_process_center.tooltips.2", "Circuit 2: Crushing-Crushing-Centrifugation", "电路2: 粉碎-粉碎-离心");
        provider.add("com.gtecore.ore_process_center.tooltips.3", "Circuit 3: Crushing-Washing-Thermal Separation-Crushing", "电路3: 粉碎-洗矿-热离-粉碎");
        provider.add("com.gtecore.ore_process_center.tooltips.4", "Circuit 4: Crushing-Thermal Separation-Crushing", "电路4: 粉碎-热离-粉碎");
        provider.add("com.gtecore.ore_process_center.tooltips.5", "Circuit 5: Crushing-Washing-Crushing-Washing", "电路5: 粉碎-洗矿-粉碎-洗矿");
        provider.add("com.gtecore.ore_process_center.tooltips.6", "Circuit 6: Crushing-Washing-Crushing-Centrifugation", "电路6: 粉碎-洗矿-粉碎-离心");
        provider.add("com.gtecore.ore_process_center.tooltips.7", "Circuit 8: Crushing-Washing-Crushing-Electromagnetic Separation", "电路8: 粉碎-洗矿-粉碎-电磁选矿");
        provider.add("com.gtecore.ore_process_center.tooltips.8", "Support subtick overclock", "支持1T OC");
        provider.add("block.gtecore.star_core_cooling_matrix","§3 Star Core Cooling Matrix","§3 星核冷却矩阵");
        provider.add("block.gtecore.max_super_battery_buffer_1x","§c§lMaximum Voltage§r Super Battery Buffer","§c上限压§r超级电池箱（§c§lMAX§r）");
        provider.add("block.gtecore.me_steam_hatch","ME Steam Hatch","ME蒸汽仓");
        provider.add("block.gtecore.not_hard_box","Not §6Hard §3B§2o§1x","§6不§3难§2之§1盒");
        provider.add("com.gtecore.not_hard_box.tooltips.0","Electricity version of the §6Easy §3B§2o§1x", "§6简§3单§2之§1盒§r的电力版本");
        provider.add("com.gtecore.tooltips.10","Can Use MultiParallel Hatch","可使用跨配方并行仓");
        provider.add("block.gtecore.large_general_generator","Large General Generator","大型通用发电机");
        provider.add("block.gtecore.wiremill_factory","§6 Wiremill Factory","§6 导线工厂");
        provider.add("gtecore.wiremill_factory","§6 Wiremill Factory","§6 导线工厂");
        provider.add("com.gtecore.wiremill_factory.tooltips.0","§6Wiremill Factory§r can make all types of wiremills","§6导线工厂§r可以制造各种种类的导线");
        provider.add("gtecore.crystal_center","§6 Crystal Center","§6 晶核中枢");
        provider.add("block.gtecore.crystal_center","§6 Crystal Center","§6 晶核中枢");
        provider.add("gtecore.quantum_cable_assembler","§6 Quantum Cable Assembler","§6 量子线擎");
        provider.add("block.gtecore.quantum_cable_assembler","§6 Quantum Cable Assembler","§6 量子线擎");
        provider.add("gtecore.starblade_etching","§3 Starblade Etching","§3星刃蚀刻");
        provider.add("block.gtecore.starblade_etching_machine","§3 Starblade Etching","§3星刃蚀刻仪");
        provider.add("item.gtecore.yin_yang_processor.tooltip.0","§7Yin gives rise to Yang, and Yang gives rise to Yin","§7阴生阳，阳生阴");
        provider.add("item.gtecore.yin_yang_processor.tooltip.1","§8UV-Level Circuits","§8UV级电路");
        provider.add("item.gtecore.yin_yang_processor","Ying Yang Processor","阴阳处理器");
        provider.add("item.gtecore.yin_yang_processor_assembly.tooltip.0","§7Yin gives rise to Yang, and Yang gives rise to Yin","§7阴生阳，阳生阴");
        provider.add("item.gtecore.yin_yang_processor_assembly.tooltip.1","§8UHV-Level Circuits","§8UHV级电路");
        provider.add("item.gtecore.yin_yang_processor_assembly","Ying Yang Processor Assembly","阴阳处理器集群");
        provider.add("item.gtecore.yin_yang_processor_computer.tooltip.0","§7Yin gives rise to Yang, and Yang gives rise to Yin","§7阴生阳，阳生阴");
        provider.add("item.gtecore.yin_yang_processor_computer.tooltip.1","§8UEV-Level Circuits","§8UEV级电路");
        provider.add("item.gtecore.yin_yang_processor_computer","Ying Yang Processor Computer","阴阳处理器超级计算机");
        provider.add("item.gtecore.yin_yang_processor_mainframe.tooltip.0","§7Yin gives rise to Yang, and Yang gives rise to Yin","§7阴生阳，阳生阴");
        provider.add("item.gtecore.yin_yang_processor_mainframe.tooltip.1","§8UIV-Level Circuits","§8UIV级电路");
        provider.add("item.gtecore.yin_yang_processor_mainframe","Ying Yang Processor Mainframe","阴阳处理器主机");
        provider.add("block.gtecore.antimatter_ball","§5 Antimatter Ball","§5暗能脉冲反物质核心");
        provider.add("gtecore.antimatter_transformation","§5 Antimatter Transformation","§5反物质变换");
        provider.add("block.gtecore.eight_trigmas_casing","§8Eight Trigmas Casing","§8八卦机械方块");
        provider.add("block.gtecore.yin_yang_coil_block","§8Yin Yang Coil Block","§8阴阳线圈方块");
        provider.add("material.gtecore.huo","§4Fire Element","§4火元素");
        provider.add("material.gtecore.shuiyuansu","§3Water Element","§3水元素");
        provider.add("material.gtecore.jinyuansu","§eGold Element","§e金元素");
        provider.add("material.gtecore.muyuansu","§2Wood Element","§2木元素");
        provider.add("material.gtecore.tuyuansu","§8Earth Element","§8土元素");
        provider.add("item.gtecore.rune_dui","Rune Dui","兑象");
        provider.add("item.gtecore.rune_gen","Rune Gen","艮象");
        provider.add("item.gtecore.rune_kan","Rune Kan","坎象");
        provider.add("item.gtecore.rune_kun","Rune Kun","坤象");
        provider.add("item.gtecore.rune_li","Rune Li","离象");
        provider.add("item.gtecore.rune_qian","Rune Qian","乾象");
        provider.add("item.gtecore.rune_xun","Rune Xun","巽象");
        provider.add("item.gtecore.rune_zhen","Rune Zhen","震象");
        provider.add("item.gtecore.symbol_paper_earth","§8Paper of Earth","§8地之符篆");
        provider.add("item.gtecore.symbol_paper_fire","§4Symbol Paper of Fire","§4火之符篆");
        provider.add("item.gtecore.symbol_paper_water","§3Symbol Paper of Water","§3水之符篆");
        provider.add("item.gtecore.symbol_paper_wood","§2Symbol Paper of Wood","§2木之符篆");
        provider.add("item.gtecore.yin","§8Yin","§8阴");
        provider.add("item.gtecore.yang","Yang","阳");
        provider.add("item.gtecore.dui_chip","Dui Chip","兑芯");
        provider.add("item.gtecore.gen_chip","Gen Chip","艮芯");
        provider.add("item.gtecore.god_nugget","God Nugget","三清之粒");
        provider.add("item.gtecore.yin_yang_wafer","§8Yin§rYang Wafer","§8阴§r阳薄片");
        provider.add("block.gtecore.kan_shui_casing","§3Kan Shui Casing","§3坎水机械方块");
        provider.add("block.gtecore.kun_gen_casing","§8Kun Gen Casing","§8坤艮机械方块");
        provider.add("block.gtecore.li_huo_casing","§4Li Huo Casing","§4离火机械方块");
        provider.add("item.gtecore.yinyang_glass_lens","§8Yin §rYang Glass Lens","§8阴§r阳透镜");
        provider.add("block.gtecore.base_dark_concrete","Base Dark Concrete","§8阴极§r混凝土");
        provider.add("block.gtecore.base_light_concrete","Base Light Concrete","阳盛混凝土");
        provider.add("block.gtecore.base_mid_concrete","Base Medium Concrete","中庸混凝土");
        provider.add("block.gtecore.yin_yang_field_restriction","§8Yin §rYang Field Restriction","§8阴§r阳立场约束方块");

    }

}
