publishing {
    publications {
        mavenJava(MavenPublication) {
            artifactId = base.archivesName.get()
            if (tasks.findByName("reobfSlimJar")) {
                artifact(tasks.named("reobfSlimJar"))
            }
            from components.java
        }
    }

    repositories {
        maven {
            name = "LocalMaven"
            url = uri(project.findProperty("mavenDir") ?: "${rootDir}/build/maven")
        }
    }
}