repositories {
    flatDir {
        dir "${projectDir}/gradle/libs"
    }
    mavenLocal()
    mavenCentral()

    maven { // JEI
        name = "Jared's Maven"
        url = "https://maven.blamejared.com/"
    }

    maven { // JEI mirror, AE2
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven { // LDLib, Shimmer
        name = "FirstDarkDev Maven"
        url = "https://maven.firstdarkdev.xyz/snapshots"
    }

    maven { // Configuration
        name = 'Configuration'
        url = 'https://api.repsy.io/mvn/toma/public/'
    }

    maven {
        name = 'GregTech Modern'
        url = "https://maven.gtceu.com"
        content {
            includeGroup "com.gregtechceu.gtceu"
        }
    }

    maven {
        name = 'CreateMod'
        url = "https://maven.createmod.net"
    }

    maven {
        name = 'Latvian'
        url = "https://maven.latvian.dev/releases"
    }

    maven {
        name = 'FTB'
        url = "https://maven.ftb.dev/releases"
    }

    maven {
        name = 'TOP'
        url = "https://maven.k-4u.nl"
    }

    maven {
        name = 'JourneyMap'
        url = "https://jm.gserv.me/repository/maven-public/"
    }

    maven {
        name = 'Modrinth'
        url = "https://api.modrinth.com/maven"
    }

    maven {
        name = 'CurseMaven'
        url = "https://cursemaven.com"
        content { includeGroup "curse.maven" }
    }

    maven {
        name = 'Terraformers'
        url = "https://maven.terraformersmc.com/releases/"
    }

    maven {
        name = 'shedaniel'
        url = "https://maven.shedaniel.me/"
    }

    maven {
        name = 'tterrag'
        url = "https://maven.tterrag.com/"
    }

    maven {
        name = 'Curios'
        url = "https://maven.theillusivec4.top/"
    }

    maven {
        name = 'KotlinForForge'
        url = "https://thedarkcolour.github.io/KotlinForForge/"
    }

    maven {
        name = 'SquidDev'
        url = "https://maven.squiddev.cc"
    }
}
