dependencies {
    compileOnly(libs.jetbrains.annotations)

    // Mixin (& Extras)
    annotationProcessor(variantOf(libs.mixin) { classifier("processor") })
    api(annotationProcessor(forge.mixinExtras.common.get()))
    
    // LDLib (provided by gtm-reborn / FirstDarkDev)
    modCompileOnly(forge.ldlib)
    
    // Registrate (provided by gtm-reborn)
    modCompileOnly(forge.registrate)

    // Configuration
    modCompileOnly(forge.configuration)
    
    // -----------------------------------------------------------------------
    // Direct Cross-Module Source Dependency to gtm-reborn
    // -----------------------------------------------------------------------
    implementation(project(':modules:gtm-reborn')) {
        transitive = false
    }
    compileOnly(project(':modules:gtm-reborn').sourceSets.main.output)

    // GregTech Addons
    modCompileOnly("blank:gtmthings:1.5.4")
    implementation(project(':modules:gt--')) {
        transitive = false
    }
    compileOnly(project(':modules:gt--').sourceSets.main.output)
    
    // Recipe Viewers
    modCompileOnly(forge.bundles.jei)

    // WAILA-likes
    modCompileOnly(forge.jade)

    // Curios
    modCompileOnly(forge.curios)
    
    // AE2
    modCompileOnly(forge.ae2)
    modCompileOnly(forge.ae2wtlib)
    modCompileOnly(forge.extendedae)

    // FTB
    modCompileOnly(forge.architectury)

    // KubeJS
    modCompileOnly(forge.kubejs)
    modCompileOnly(forge.rhino)

    // Shimmer / Render
    modCompileOnly(forge.shimmer)
    modCompileOnly(forge.embeddium)
    modCompileOnly(forge.oculus)
    modCompileOnly(forge.modernfix)

    modCompileOnly(forge.guideme)

    modLocalRuntime(forge.configuration)
    // Standard runtime mods //
    modClientLocalRuntime(forge.jade)
    modLocalRuntime(forge.curios)
    modLocalRuntime(forge.modernfix)
    modClientLocalRuntime(forge.modernui)
    modLocalRuntime(forge.ferritecore)

    modLocalRuntime(forge.glodium)
    modLocalRuntime(forge.clothconfig)
    // AE2 //
    modLocalRuntime(forge.guideme)
    modLocalRuntime(forge.ae2)
    modLocalRuntime(forge.ae2wtlib)
    modLocalRuntime(forge.extendedae)

    modLocalRuntime("curse.maven:ldlib-626676:6995785")

    // FTB //
    modLocalRuntime(forge.architectury)

    // Sophisticated Mods //
    modLocalRuntime(forge.sophisticatedcore)
    modLocalRuntime(forge.sophisticatedbackpacks)
    modLocalRuntime(forge.sophisticatedstorage)

    // Runtime Recipe Viewers //
    modLocalRuntime(forge.jei.forge.impl)

    // Ponder / Flywheel //
    modLocalRuntime(forge.ponder)
    modLocalRuntime(forge.flywheel.forge)

    // Client-only runtime mods //
    modClientLocalRuntime(forge.embeddium)
    modClientLocalRuntime(forge.oculus)
    renderNurseCfg(libs.renderNurse)

    // GregTech Addon Runtime
    modLocalRuntime("blank:gtmthings:1.5.4")
    modLocalRuntime("blank:gtnn:1.20.1-1.3.5.3")
}